const Itemdata = [
    {
      id:   1,
      image : '../imgcontent/hijab1.jpg',
      namaBarang: 'Baju',
      qty: '5',
      status: 'ada',
      kategori: 'anak-anak',
      harga: '200000',
    },
    {
        id: 2,
        namaBarang: 'celana',
        image:'../imgcontent/hijab3.png',
        qty: '5',
        status: 'Preorder',
        kategori: 'remaja',
        harga: '200000',
    },
    {
     id: 3,
     namaBarang: 'jeans',
     image:'../imgcontent/hijab4.jpg',
     qty : '6',
     status: 'ada',
     kategori: 'dewasa',
     harga: '200000',
    },
    {
      id: 4,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'Preorder',
      kategori: 'dewasa',
      harga: '200000',
     },
     {
      id: 5,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'ada',
      kategori: 'dewasa',
      harga: '200000',
     },
     {
      id: 6,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'ada',
      kategori: 'dewasa',
      harga: '200000',
     },
     {
      id: 7,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'ada',
      kategori: 'dewasa',
      harga: '200000',
     },
     
     {
      id: 8,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'ada',
      kategori: 'dewasa',
      harga: '200000',
     },
     {
      id: 9,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'ada',
      kategori: 'dewasa',
      harga: '200000',
     },
     {
      id: 10,
      namaBarang: 'jeans',
      image:'../imgcontent/hijab4.jpg',
      qty : '6',
      status: 'ada',
      kategori: 'dewasa',
      harga: '200000',
     },
  ];
  
  export { Itemdata};